// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TunzWorkout.Infrastructure.Data;

#nullable disable

namespace TunzWorkout.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241123043446_addDb")]
    partial class addDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TunzWorkout.Domain.Entities.EquipmentImages.EquipmentImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("EquipmentImages");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Equipments.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.ExerciseEquipments.ExerciseEquipment", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExerciseId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("ExerciseEquipments");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.ExerciseMuscles.ExerciseMuscle", b =>
                {
                    b.Property<Guid>("MuscleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MuscleId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ExerciseMuscles");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasEquipment")
                        .HasColumnType("bit");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.FitnessProfiles.FitnessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("FitnessProfiles");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Goals.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Levels.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.MuscleImages.MuscleImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MuscleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MuscleId");

                    b.ToTable("MuscleImages");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Muscles.Muscle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Muscles");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.RoundExercises.RoundExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Rest")
                        .HasColumnType("int");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("RoundId");

                    b.ToTable("RoundExercises");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Rounds.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Rest")
                        .HasColumnType("int");

                    b.Property<int>("Set")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.UserGoals.UserGoal", b =>
                {
                    b.Property<Guid>("FitnessProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FitnessProfileId", "GoalId");

                    b.HasIndex("GoalId");

                    b.ToTable("UserGoals");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Videos.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Workouts.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("LevelId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.EquipmentImages.EquipmentImage", b =>
                {
                    b.HasOne("TunzWorkout.Domain.Entities.Equipments.Equipment", "Equipment")
                        .WithMany("EquipmentImages")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.ExerciseEquipments.ExerciseEquipment", b =>
                {
                    b.HasOne("TunzWorkout.Domain.Entities.Equipments.Equipment", "Equipment")
                        .WithMany("ExerciseEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunzWorkout.Domain.Entities.Exercises.Exercise", "Exercise")
                        .WithMany("ExerciseEquipments")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.ExerciseMuscles.ExerciseMuscle", b =>
                {
                    b.HasOne("TunzWorkout.Domain.Entities.Exercises.Exercise", "Exercise")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunzWorkout.Domain.Entities.Muscles.Muscle", "Muscle")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Exercises.Exercise", b =>
                {
                    b.HasOne("TunzWorkout.Domain.Entities.Levels.Level", "Level")
                        .WithMany("Exercises")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.FitnessProfiles.FitnessProfile", b =>
                {
                    b.HasOne("TunzWorkout.Domain.Entities.Levels.Level", "Level")
                        .WithMany("FitnessProfiles")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunzWorkout.Domain.Entities.Users.User", "User")
                        .WithOne("FitnessProfile")
                        .HasForeignKey("TunzWorkout.Domain.Entities.FitnessProfiles.FitnessProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.MuscleImages.MuscleImage", b =>
                {
                    b.HasOne("TunzWorkout.Domain.Entities.Muscles.Muscle", "Muscle")
                        .WithMany("MuscleImages")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.RoundExercises.RoundExercise", b =>
                {
                    b.HasOne("TunzWorkout.Domain.Entities.Exercises.Exercise", "Exercise")
                        .WithMany("RoundExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunzWorkout.Domain.Entities.Rounds.Round", "Round")
                        .WithMany("RoundExercises")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Rounds.Round", b =>
                {
                    b.HasOne("TunzWorkout.Domain.Entities.Workouts.Workout", "Workout")
                        .WithMany("Rounds")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.UserGoals.UserGoal", b =>
                {
                    b.HasOne("TunzWorkout.Domain.Entities.FitnessProfiles.FitnessProfile", "FitnessProfile")
                        .WithMany("UserGoals")
                        .HasForeignKey("FitnessProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunzWorkout.Domain.Entities.Goals.Goal", "Goal")
                        .WithMany("UserGoals")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FitnessProfile");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Videos.Video", b =>
                {
                    b.HasOne("TunzWorkout.Domain.Entities.Exercises.Exercise", "Exercise")
                        .WithMany("Videos")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Workouts.Workout", b =>
                {
                    b.HasOne("TunzWorkout.Domain.Entities.Goals.Goal", "Goal")
                        .WithMany("Workouts")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunzWorkout.Domain.Entities.Levels.Level", "Level")
                        .WithMany("Workouts")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Equipments.Equipment", b =>
                {
                    b.Navigation("EquipmentImages");

                    b.Navigation("ExerciseEquipments");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Exercises.Exercise", b =>
                {
                    b.Navigation("ExerciseEquipments");

                    b.Navigation("ExerciseMuscles");

                    b.Navigation("RoundExercises");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.FitnessProfiles.FitnessProfile", b =>
                {
                    b.Navigation("UserGoals");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Goals.Goal", b =>
                {
                    b.Navigation("UserGoals");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Levels.Level", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("FitnessProfiles");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Muscles.Muscle", b =>
                {
                    b.Navigation("ExerciseMuscles");

                    b.Navigation("MuscleImages");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Rounds.Round", b =>
                {
                    b.Navigation("RoundExercises");
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("FitnessProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("TunzWorkout.Domain.Entities.Workouts.Workout", b =>
                {
                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
